const thumbs = [
  require("../assets/thumbs/biblio/biblio.jpg"),
  require("../assets/thumbs/biblio/vergne.jpg"),
  require("../assets/thumbs/biblio/salon.jpg"),
  require("../assets/thumbs/biblio/IMG20.jpg"),
  require("../assets/thumbs/biblio/salonAr.jpg"),
  require("../assets/thumbs/biblio/DSC0045.jpg"),
  require("../assets/thumbs/biblio/biblioSAlon.jpg"),
  require("../assets/thumbs/dressing/dressing.jpg"),
  require("../assets/thumbs/dressing/bedroom.jpg"),
  require("../assets/thumbs/dressing/img.jpg"),
  require("../assets/thumbs/dressing/lightFirst.jpg"),
  require("../assets/thumbs/dressing/light.jpg"),
  require("../assets/thumbs/dressing/miniDress.jpg"),
  require("../assets/thumbs/dressing/whiteDress.jpg"),
  require("../assets/thumbs/dressing/autreDress.jpg"),
  require("../assets/thumbs/dressing/mini.jpeg"),
  require("../assets/thumbs/dressing/sorinAutre.jpeg"),
  require("../assets/thumbs/dressing/sorin.jpeg"),
  // require("../assets/thumbs/dressing/img.jpg"),
  // require("../assets/thumbs/dressing/lightFirst.jpg"),
  // require("../assets/thumbs/dressing/light.jpg"),
];

export default thumbs;
